---
- name: test the collection
  hosts: all
  gather_facts: false
  vars:
    blueprint_src_path: "/tmp/testblueprint.toml"
  tasks:
    - name: create a blueprint
      osbuild.composer.create_blueprint:
        dest: "{{ blueprint_src_path }}"
        name: "my-rhel-edge-test"
        version: "0.0.1"
        packages:
          - "vim-enhanced"
          - "ansible-core"
          - "git"

    - name: push the blueprint into image builder
      osbuild.composer.push_blueprint:
        src: "{{ blueprint_src_path }}"

    - name: start compose
      osbuild.composer.start_compose:
        blueprint: "my-rhel-edge-test"
        compose_type: "edge-commit"
      register: compose_start_out

    - debug: var=compose_start_out

    - name: wait for compose to finish
      osbuild.composer.wait_compose:
        compose_id: "{{ compose_start_out['result']['build_id'] }}"
